POST http://localhost:3000/api/class/
Content-Type: application/json

{
  "class_name":"Maths",
  "time_in_pakistan":12
}

### 4. Update Specific
PUT http://localhost:3000/api/class/6029682e-ac6d-4210-b730-d2fa28507b53
Content-Type: application/json

{
    "class_name": "Calculus",
    "time_in_pakistan": 15
}

### DELETE SPECIFIC CLASS
DELETE  http://localhost:3000/api/class/58a3a2ad-d2c3-4d8a-a6a7-5f46f83bb69f

### 3. Get Specific (Replace with a real UUID from your DB)
GET http://localhost:3000/api/class/96df342f-5b60-46a0-b744-366afa123210

### 4. Get Specific classes Students (Replace with a real UUID from your DB)
GET http://localhost:3000/api/class/96df342f-5b60-46a0-b744-366afa123210/students

### 5. POST a student linked to a class (Replace with a real UUID from your DB)

POST http://localhost:3000/api/class/96df342f-5b60-46a0-b744-366afa123210/students
Content-Type: application/json

{
  "name":"Bablo",
  "email":"mzkhan886@gmail.com"
  
}
